### PR TITLE
master-qa-57195

### PR DESCRIPTION
**Pull request by SylviaLuan**
https://issues.liferay.com/browse/LRQA-57195
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/29941

/cc @brianwulbern

### CODE REVIEW

**Comment by SylviaLuan** [comment]
ci:test:sf

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
ci:forward

**Pull request closed without merging**
