### PR TITLE
master-qa-64691

### PR DESCRIPTION
**Pull request by felix3508**
https://issues.liferay.com/browse/LRQA-64691

### CODE REVIEW

**Comment by felix3508** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
ci:stop

**Comment by yunlinsun** [comment]
ci:stop

**Comment by yunlinsun** [comment]
ci:reevaluate:1072004_6644

**Comment by yunlinsun** [comment]
ci:reevaluate

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
Pushed to BChan.
https://github.com/yunlinsun/liferay-portal/pull/80

**Pull request closed without merging**
