### PR TITLE
Master-qa-54776

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LRQA-54776

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by HarryC0204** [comment]
ci:test:acceptance

**Comment by HarryC0204** [comment]
cc. @brianwulbern

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by HarryC0204** [comment]
ci:test:acceptance

**Comment by yunlinsun** [comment]
ci:forward

**Pull request closed without merging**
