### PR TITLE
master-qa-63833

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-63833
7.3.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/32970
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/32969

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
ci:forward

**Comment by yunlinsun** [comment]
cc @brianwulbern

**Pull request closed without merging**
