### PR TITLE
master-qa-62916

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-62916
7.3.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/32394

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:bundle

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
ci:forward

**Pull request closed without merging**
