### PR TITLE
master-qa-59714

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-59714

cc @brianwulbern

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
Hi @melodywu , could you please remove the property `portal.upstream = "quarantine";` on line 4733? Thanks!

**Comment by yunlinsun** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
ci:forward

**Pull request closed without merging**
