### PR TITLE
master-qa-54429

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-54429

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
ci:forward

**Comment by melodywu** [comment]
ci:forward

**Comment by yunlinsun** [comment]
@melodywu , please run `ant -f build-test.xml run-poshi-validation` on your host before push to me. Thanks.

**Comment by melodywu** [comment]
Ok thanks

**Pull request closed without merging**
