### PR TITLE
master-qa-64823

### PR DESCRIPTION
**Pull request by yunlinsun**
https://issues.liferay.com/browse/LRQA-64823
7.3.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/33258
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/33259
7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/33262
7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/33261

cc @brianwulbern @michaelhashimoto @yichenroy

### CODE REVIEW

**Comment by yunlinsun** [comment]
ci:forward

**Comment by yunlinsun** [comment]
ci:forward

**Comment by yunlinsun** [comment]
ci:reevaluate

**Comment by yichenroy** [comment]
Thanks @yunlinsun , I think this should work fine, was this tested somewhere?

**Comment by yunlinsun** [comment]
@yichenroy , yes, I tested [here](https://testray.liferay.com/home/-/testray/runs?tab=results&testrayBuildId=1472274597).The results looks good.

**Pull request closed without merging**
