### PR TITLE
LRQA-66719 Automate LPS-124984

### PR DESCRIPTION
**Pull request by Wa1ter-Shao**
https://issues.liferay.com/browse/LRQA-66719

### CODE REVIEW

**Comment by Wa1ter-Shao** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
@Wa1ter-Shao , please fix the SF error first

**Comment by yunlinsun** [comment]
@Wa1ter-Shao , even this is a practise. You should follow our standard. Please force repush to leave only one commit instead of two commits.

**Comment by Wa1ter-Shao** [comment]
@yunlinsun roger that.

**Pull request closed without merging**
