### PR TITLE
master-qa-71007

### PR DESCRIPTION
**Pull request by felix3508**
https://issues.liferay.com/browse/LRQA-71007
https://github.com/brianchandotcom/liferay-portal-ee/pull/35798
https://github.com/brianchandotcom/liferay-portal-ee/pull/35794
https://github.com/brianchandotcom/liferay-portal-ee/pull/35796
https://github.com/brianchandotcom/liferay-portal-ee/pull/35797

cc @brianwulbern

### CODE REVIEW

**Comment by felix3508** [comment]
ci:test:sf

**Comment by felix3508** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
ci:forward

**Pull request closed without merging**
