### PR TITLE
LRQA-69166, LRQA-69376 | master

### PR DESCRIPTION
**Pull request by Songyuewen**
https://issues.liferay.com/browse/LRQA-69166
https://issues.liferay.com/browse/LRQA-69376
7.3.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/35162
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/35159
7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/35160
7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/35161

### CODE REVIEW

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:sf

**Comment by Songyuewen** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
ci:forward

**Pull request closed without merging**
