### PR TITLE
master-qa-69197

### PR DESCRIPTION
**Pull request by SylviaLuan**
https://issues.liferay.com/browse/LRQA-69197
7.3.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/35188
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/35185
7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/35186
7.0.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/35187

/cc @brianwulbern

### CODE REVIEW

**Comment by SylviaLuan** [comment]
ci:test:sf

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by yunlinsun** [comment]
@SylviaLuan , it looks good to backport all to the other branches.

**Comment by yunlinsun** [comment]
ci:forward

**Pull request closed without merging**
