### PR TITLE
master-qa-59703

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-59703
7.3.x: https://github.com/yunlinsun/liferay-portal-ee/pull/806
7.2.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/33932
7.1.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/33933

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
@melodywu good job! 
It seems like this issue also reproducible on [7.2.x](https://testray.liferay.com/home/-/testray/cases/439711511), [7.1.x](https://testray.liferay.com/home/-/testray/cases/220056706) and [7.0.x](https://testray.liferay.com/home/-/testray/cases/212292757)
Can you backport your fix to those branches? Thanks

cc @brianwulbern

**Comment by melodywu** [comment]
ci:test:relevant

**Comment by melodywu** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
@melodywu sf failure unrelated to your changes.

```
  [java] 1: ./build.properties expected:<...al,\
     [java]     #    apps/s[]taging,\
     [java]     #    ap...> but was:<...al,\
     [java]     #    apps/s[ocial-bookmarks,\
     [java]     #    apps/s]taging,\
     [java]     #    ap...>
```

**Comment by melodywu** [comment]
> @melodywu sf failure unrelated to your changes.
> 
> ```
>   [java] 1: ./build.properties expected:<...al,\
>      [java]     #    apps/s[]taging,\
>      [java]     #    ap...> but was:<...al,\
>      [java]     #    apps/s[ocial-bookmarks,\
>      [java]     #    apps/s]taging,\
>      [java]     #    ap...>
> ```

@brianwulbern , OK thanks

**Comment by yunlinsun** [comment]
ci:test:sf

**Comment by yunlinsun** [comment]
ci:forward

**Pull request closed without merging**
